namespace Pharmacy_System
{
    partial class Employee
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Employee));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            DataGridViewCellStyle dataGridViewCellStyle1 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle2 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle3 = new DataGridViewCellStyle();
            numage = new NumericUpDown();
            numsalary = new NumericUpDown();
            comboBoxgender = new ComboBox();
            bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            emp_name = new Bunifu.UI.WinForms.BunifuTextBox();
            label2 = new Label();
            label1 = new Label();
            txt_phone = new Bunifu.UI.WinForms.BunifuTextBox();
            txt_password = new Bunifu.UI.WinForms.BunifuTextBox();
            btn_add = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            btn_back = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            btn_delete = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            btn_Update = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            label3 = new Label();
            dgv_emp = new Bunifu.UI.WinForms.BunifuDataGridView();
            comboRole = new ComboBox();
            ((System.ComponentModel.ISupportInitialize)numage).BeginInit();
            ((System.ComponentModel.ISupportInitialize)numsalary).BeginInit();
            ((System.ComponentModel.ISupportInitialize)dgv_emp).BeginInit();
            SuspendLayout();
            // 
            // numage
            // 
            numage.Location = new Point(17, 209);
            numage.Name = "numage";
            numage.Size = new Size(177, 27);
            numage.TabIndex = 20;
            // 
            // numsalary
            // 
            numsalary.Location = new Point(274, 124);
            numsalary.Maximum = new decimal(new int[] { 100000, 0, 0, 0 });
            numsalary.Name = "numsalary";
            numsalary.Size = new Size(177, 27);
            numsalary.TabIndex = 19;
            numsalary.ValueChanged += numbprice_ValueChanged;
            // 
            // comboBoxgender
            // 
            comboBoxgender.Font = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point);
            comboBoxgender.ForeColor = Color.Maroon;
            comboBoxgender.FormattingEnabled = true;
            comboBoxgender.Items.AddRange(new object[] { "Male", "Female" });
            comboBoxgender.Location = new Point(300, 208);
            comboBoxgender.Name = "comboBoxgender";
            comboBoxgender.Size = new Size(151, 28);
            comboBoxgender.TabIndex = 18;
            comboBoxgender.Text = "Gender";
            // 
            // bunifuLabel1
            // 
            bunifuLabel1.AllowParentOverrides = false;
            bunifuLabel1.AutoEllipsis = false;
            bunifuLabel1.CursorType = Cursors.Default;
            bunifuLabel1.Font = new Font("Arial Narrow", 18F, FontStyle.Bold, GraphicsUnit.Point);
            bunifuLabel1.ForeColor = Color.DarkRed;
            bunifuLabel1.Location = new Point(40, 25);
            bunifuLabel1.Name = "bunifuLabel1";
            bunifuLabel1.RightToLeft = RightToLeft.No;
            bunifuLabel1.Size = new Size(117, 35);
            bunifuLabel1.TabIndex = 17;
            bunifuLabel1.Text = "Employee";
            bunifuLabel1.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // emp_name
            // 
            emp_name.AcceptsReturn = false;
            emp_name.AcceptsTab = false;
            emp_name.AnimationSpeed = 200;
            emp_name.AutoCompleteMode = AutoCompleteMode.None;
            emp_name.AutoCompleteSource = AutoCompleteSource.None;
            emp_name.AutoSizeHeight = true;
            emp_name.BackColor = Color.Transparent;
            emp_name.BackgroundImage = (Image)resources.GetObject("emp_name.BackgroundImage");
            emp_name.BorderColorActive = Color.DodgerBlue;
            emp_name.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            emp_name.BorderColorHover = Color.FromArgb(64, 0, 0);
            emp_name.BorderColorIdle = Color.Silver;
            emp_name.BorderRadius = 1;
            emp_name.BorderThickness = 1;
            emp_name.CharacterCasing = CharacterCasing.Normal;
            emp_name.DefaultFont = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point);
            emp_name.DefaultText = "";
            emp_name.FillColor = Color.White;
            emp_name.HideSelection = true;
            emp_name.IconLeft = null;
            emp_name.IconLeftCursor = Cursors.IBeam;
            emp_name.IconPadding = 10;
            emp_name.IconRight = null;
            emp_name.IconRightCursor = Cursors.IBeam;
            emp_name.Location = new Point(17, 107);
            emp_name.MaxLength = 32767;
            emp_name.MinimumSize = new Size(1, 1);
            emp_name.Modified = false;
            emp_name.Multiline = false;
            emp_name.Name = "emp_name";
            stateProperties1.BorderColor = Color.DodgerBlue;
            stateProperties1.FillColor = Color.Empty;
            stateProperties1.ForeColor = Color.Empty;
            stateProperties1.PlaceholderForeColor = Color.Empty;
            emp_name.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties2.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties2.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties2.PlaceholderForeColor = Color.DarkGray;
            emp_name.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = Color.FromArgb(64, 0, 0);
            stateProperties3.FillColor = Color.Empty;
            stateProperties3.ForeColor = Color.Empty;
            stateProperties3.PlaceholderForeColor = Color.Empty;
            emp_name.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = Color.Silver;
            stateProperties4.FillColor = Color.White;
            stateProperties4.ForeColor = Color.Empty;
            stateProperties4.PlaceholderForeColor = Color.Empty;
            emp_name.OnIdleState = stateProperties4;
            emp_name.Padding = new Padding(3);
            emp_name.PasswordChar = '\0';
            emp_name.PlaceholderForeColor = Color.Maroon;
            emp_name.PlaceholderText = "Employee Name";
            emp_name.ReadOnly = false;
            emp_name.ScrollBars = ScrollBars.None;
            emp_name.SelectedText = "";
            emp_name.SelectionLength = 0;
            emp_name.SelectionStart = 0;
            emp_name.ShortcutsEnabled = true;
            emp_name.Size = new Size(189, 42);
            emp_name.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            emp_name.TabIndex = 16;
            emp_name.TextAlign = HorizontalAlignment.Left;
            emp_name.TextMarginBottom = 0;
            emp_name.TextMarginLeft = 3;
            emp_name.TextMarginTop = 1;
            emp_name.TextPlaceholder = "Employee Name";
            emp_name.UseSystemPasswordChar = false;
            emp_name.WordWrap = true;
            // 
            // label2
            // 
            label2.AutoSize = true;
            label2.Font = new Font("Segoe UI", 10.2F, FontStyle.Bold, GraphicsUnit.Point);
            label2.ForeColor = Color.Maroon;
            label2.Location = new Point(316, 84);
            label2.Name = "label2";
            label2.Size = new Size(60, 23);
            label2.TabIndex = 22;
            label2.Text = "Salary";
            // 
            // label1
            // 
            label1.AutoSize = true;
            label1.Font = new Font("Segoe UI", 10.2F, FontStyle.Bold, GraphicsUnit.Point);
            label1.ForeColor = Color.Maroon;
            label1.Location = new Point(56, 171);
            label1.Name = "label1";
            label1.Size = new Size(42, 23);
            label1.TabIndex = 23;
            label1.Text = "Age";
            // 
            // txt_phone
            // 
            txt_phone.AcceptsReturn = false;
            txt_phone.AcceptsTab = false;
            txt_phone.AnimationSpeed = 200;
            txt_phone.AutoCompleteMode = AutoCompleteMode.None;
            txt_phone.AutoCompleteSource = AutoCompleteSource.None;
            txt_phone.AutoSizeHeight = true;
            txt_phone.BackColor = Color.Transparent;
            txt_phone.BackgroundImage = (Image)resources.GetObject("txt_phone.BackgroundImage");
            txt_phone.BorderColorActive = Color.DodgerBlue;
            txt_phone.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txt_phone.BorderColorHover = Color.FromArgb(64, 0, 0);
            txt_phone.BorderColorIdle = Color.Silver;
            txt_phone.BorderRadius = 1;
            txt_phone.BorderThickness = 1;
            txt_phone.CharacterCasing = CharacterCasing.Normal;
            txt_phone.DefaultFont = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point);
            txt_phone.DefaultText = "";
            txt_phone.FillColor = Color.White;
            txt_phone.HideSelection = true;
            txt_phone.IconLeft = null;
            txt_phone.IconLeftCursor = Cursors.IBeam;
            txt_phone.IconPadding = 10;
            txt_phone.IconRight = null;
            txt_phone.IconRightCursor = Cursors.IBeam;
            txt_phone.Location = new Point(23, 274);
            txt_phone.MaxLength = 32767;
            txt_phone.MinimumSize = new Size(1, 1);
            txt_phone.Modified = false;
            txt_phone.Multiline = false;
            txt_phone.Name = "txt_phone";
            stateProperties5.BorderColor = Color.DodgerBlue;
            stateProperties5.FillColor = Color.Empty;
            stateProperties5.ForeColor = Color.Empty;
            stateProperties5.PlaceholderForeColor = Color.Empty;
            txt_phone.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties6.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties6.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties6.PlaceholderForeColor = Color.DarkGray;
            txt_phone.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = Color.FromArgb(64, 0, 0);
            stateProperties7.FillColor = Color.Empty;
            stateProperties7.ForeColor = Color.Empty;
            stateProperties7.PlaceholderForeColor = Color.Empty;
            txt_phone.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = Color.Silver;
            stateProperties8.FillColor = Color.White;
            stateProperties8.ForeColor = Color.Empty;
            stateProperties8.PlaceholderForeColor = Color.Empty;
            txt_phone.OnIdleState = stateProperties8;
            txt_phone.Padding = new Padding(3);
            txt_phone.PasswordChar = '\0';
            txt_phone.PlaceholderForeColor = Color.Maroon;
            txt_phone.PlaceholderText = "phone number";
            txt_phone.ReadOnly = false;
            txt_phone.ScrollBars = ScrollBars.None;
            txt_phone.SelectedText = "";
            txt_phone.SelectionLength = 0;
            txt_phone.SelectionStart = 0;
            txt_phone.ShortcutsEnabled = true;
            txt_phone.Size = new Size(189, 42);
            txt_phone.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txt_phone.TabIndex = 24;
            txt_phone.TextAlign = HorizontalAlignment.Left;
            txt_phone.TextMarginBottom = 0;
            txt_phone.TextMarginLeft = 3;
            txt_phone.TextMarginTop = 1;
            txt_phone.TextPlaceholder = "phone number";
            txt_phone.UseSystemPasswordChar = false;
            txt_phone.WordWrap = true;
            // 
            // txt_password
            // 
            txt_password.AcceptsReturn = false;
            txt_password.AcceptsTab = false;
            txt_password.AnimationSpeed = 200;
            txt_password.AutoCompleteMode = AutoCompleteMode.None;
            txt_password.AutoCompleteSource = AutoCompleteSource.None;
            txt_password.AutoSizeHeight = true;
            txt_password.BackColor = Color.Transparent;
            txt_password.BackgroundImage = (Image)resources.GetObject("txt_password.BackgroundImage");
            txt_password.BorderColorActive = Color.DodgerBlue;
            txt_password.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txt_password.BorderColorHover = Color.FromArgb(64, 0, 0);
            txt_password.BorderColorIdle = Color.Silver;
            txt_password.BorderRadius = 1;
            txt_password.BorderThickness = 1;
            txt_password.CharacterCasing = CharacterCasing.Normal;
            txt_password.DefaultFont = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point);
            txt_password.DefaultText = "";
            txt_password.FillColor = Color.White;
            txt_password.HideSelection = true;
            txt_password.IconLeft = null;
            txt_password.IconLeftCursor = Cursors.IBeam;
            txt_password.IconPadding = 10;
            txt_password.IconRight = null;
            txt_password.IconRightCursor = Cursors.IBeam;
            txt_password.Location = new Point(274, 274);
            txt_password.MaxLength = 32767;
            txt_password.MinimumSize = new Size(1, 1);
            txt_password.Modified = false;
            txt_password.Multiline = false;
            txt_password.Name = "txt_password";
            stateProperties9.BorderColor = Color.DodgerBlue;
            stateProperties9.FillColor = Color.Empty;
            stateProperties9.ForeColor = Color.Empty;
            stateProperties9.PlaceholderForeColor = Color.Empty;
            txt_password.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties10.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties10.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties10.PlaceholderForeColor = Color.DarkGray;
            txt_password.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = Color.FromArgb(64, 0, 0);
            stateProperties11.FillColor = Color.Empty;
            stateProperties11.ForeColor = Color.Empty;
            stateProperties11.PlaceholderForeColor = Color.Empty;
            txt_password.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = Color.Silver;
            stateProperties12.FillColor = Color.White;
            stateProperties12.ForeColor = Color.Empty;
            stateProperties12.PlaceholderForeColor = Color.Empty;
            txt_password.OnIdleState = stateProperties12;
            txt_password.Padding = new Padding(3);
            txt_password.PasswordChar = '\0';
            txt_password.PlaceholderForeColor = Color.Maroon;
            txt_password.PlaceholderText = "Password";
            txt_password.ReadOnly = false;
            txt_password.ScrollBars = ScrollBars.None;
            txt_password.SelectedText = "";
            txt_password.SelectionLength = 0;
            txt_password.SelectionStart = 0;
            txt_password.ShortcutsEnabled = true;
            txt_password.Size = new Size(189, 42);
            txt_password.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txt_password.TabIndex = 25;
            txt_password.TextAlign = HorizontalAlignment.Left;
            txt_password.TextMarginBottom = 0;
            txt_password.TextMarginLeft = 3;
            txt_password.TextMarginTop = 1;
            txt_password.TextPlaceholder = "Password";
            txt_password.UseSystemPasswordChar = true;
            txt_password.WordWrap = true;
            // 
            // btn_add
            // 
            btn_add.AllowAnimations = true;
            btn_add.AllowMouseEffects = true;
            btn_add.AllowToggling = false;
            btn_add.AnimationSpeed = 200;
            btn_add.AutoGenerateColors = false;
            btn_add.AutoRoundBorders = false;
            btn_add.AutoSizeLeftIcon = true;
            btn_add.AutoSizeRightIcon = true;
            btn_add.BackColor = Color.Transparent;
            btn_add.BackColor1 = Color.Maroon;
            btn_add.BackgroundImage = (Image)resources.GetObject("btn_add.BackgroundImage");
            btn_add.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btn_add.ButtonText = "Add";
            btn_add.ButtonTextMarginLeft = 0;
            btn_add.ColorContrastOnClick = 45;
            btn_add.ColorContrastOnHover = 45;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            btn_add.CustomizableEdges = borderEdges1;
            btn_add.DialogResult = DialogResult.None;
            btn_add.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btn_add.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btn_add.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btn_add.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btn_add.Font = new Font("Segoe UI", 10.2F, FontStyle.Bold, GraphicsUnit.Point);
            btn_add.ForeColor = Color.White;
            btn_add.IconLeftAlign = ContentAlignment.MiddleLeft;
            btn_add.IconLeftCursor = Cursors.Default;
            btn_add.IconLeftPadding = new Padding(11, 3, 3, 3);
            btn_add.IconMarginLeft = 11;
            btn_add.IconPadding = 10;
            btn_add.IconRightAlign = ContentAlignment.MiddleRight;
            btn_add.IconRightCursor = Cursors.Default;
            btn_add.IconRightPadding = new Padding(3, 3, 7, 3);
            btn_add.IconSize = 25;
            btn_add.IdleBorderColor = Color.DodgerBlue;
            btn_add.IdleBorderRadius = 1;
            btn_add.IdleBorderThickness = 1;
            btn_add.IdleFillColor = Color.Maroon;
            btn_add.IdleIconLeftImage = null;
            btn_add.IdleIconRightImage = null;
            btn_add.IndicateFocus = false;
            btn_add.Location = new Point(17, 392);
            btn_add.Name = "btn_add";
            btn_add.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btn_add.OnDisabledState.BorderRadius = 1;
            btn_add.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btn_add.OnDisabledState.BorderThickness = 1;
            btn_add.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btn_add.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btn_add.OnDisabledState.IconLeftImage = null;
            btn_add.OnDisabledState.IconRightImage = null;
            btn_add.onHoverState.BorderColor = Color.FromArgb(105, 181, 255);
            btn_add.onHoverState.BorderRadius = 1;
            btn_add.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btn_add.onHoverState.BorderThickness = 1;
            btn_add.onHoverState.FillColor = Color.FromArgb(105, 181, 255);
            btn_add.onHoverState.ForeColor = Color.White;
            btn_add.onHoverState.IconLeftImage = null;
            btn_add.onHoverState.IconRightImage = null;
            btn_add.OnIdleState.BorderColor = Color.DodgerBlue;
            btn_add.OnIdleState.BorderRadius = 1;
            btn_add.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btn_add.OnIdleState.BorderThickness = 1;
            btn_add.OnIdleState.FillColor = Color.Maroon;
            btn_add.OnIdleState.ForeColor = Color.White;
            btn_add.OnIdleState.IconLeftImage = null;
            btn_add.OnIdleState.IconRightImage = null;
            btn_add.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btn_add.OnPressedState.BorderRadius = 1;
            btn_add.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btn_add.OnPressedState.BorderThickness = 1;
            btn_add.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btn_add.OnPressedState.ForeColor = Color.White;
            btn_add.OnPressedState.IconLeftImage = null;
            btn_add.OnPressedState.IconRightImage = null;
            btn_add.Size = new Size(126, 49);
            btn_add.TabIndex = 29;
            btn_add.TextAlign = ContentAlignment.MiddleCenter;
            btn_add.TextAlignment = HorizontalAlignment.Center;
            btn_add.TextMarginLeft = 0;
            btn_add.TextPadding = new Padding(0);
            btn_add.UseDefaultRadiusAndThickness = true;
            btn_add.Click += btn_add_Click;
            // 
            // btn_back
            // 
            btn_back.AllowAnimations = true;
            btn_back.AllowMouseEffects = true;
            btn_back.AllowToggling = false;
            btn_back.AnimationSpeed = 200;
            btn_back.AutoGenerateColors = false;
            btn_back.AutoRoundBorders = false;
            btn_back.AutoSizeLeftIcon = true;
            btn_back.AutoSizeRightIcon = true;
            btn_back.BackColor = Color.Transparent;
            btn_back.BackColor1 = Color.Maroon;
            btn_back.BackgroundImage = (Image)resources.GetObject("btn_back.BackgroundImage");
            btn_back.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btn_back.ButtonText = "Back";
            btn_back.ButtonTextMarginLeft = 0;
            btn_back.ColorContrastOnClick = 45;
            btn_back.ColorContrastOnHover = 45;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            btn_back.CustomizableEdges = borderEdges2;
            btn_back.DialogResult = DialogResult.None;
            btn_back.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btn_back.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btn_back.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btn_back.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btn_back.Font = new Font("Segoe UI", 10.2F, FontStyle.Bold, GraphicsUnit.Point);
            btn_back.ForeColor = Color.White;
            btn_back.IconLeftAlign = ContentAlignment.MiddleLeft;
            btn_back.IconLeftCursor = Cursors.Default;
            btn_back.IconLeftPadding = new Padding(11, 3, 3, 3);
            btn_back.IconMarginLeft = 11;
            btn_back.IconPadding = 10;
            btn_back.IconRightAlign = ContentAlignment.MiddleRight;
            btn_back.IconRightCursor = Cursors.Default;
            btn_back.IconRightPadding = new Padding(3, 3, 7, 3);
            btn_back.IconSize = 25;
            btn_back.IdleBorderColor = Color.DodgerBlue;
            btn_back.IdleBorderRadius = 1;
            btn_back.IdleBorderThickness = 1;
            btn_back.IdleFillColor = Color.Maroon;
            btn_back.IdleIconLeftImage = null;
            btn_back.IdleIconRightImage = null;
            btn_back.IndicateFocus = false;
            btn_back.Location = new Point(184, 475);
            btn_back.Name = "btn_back";
            btn_back.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btn_back.OnDisabledState.BorderRadius = 1;
            btn_back.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btn_back.OnDisabledState.BorderThickness = 1;
            btn_back.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btn_back.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btn_back.OnDisabledState.IconLeftImage = null;
            btn_back.OnDisabledState.IconRightImage = null;
            btn_back.onHoverState.BorderColor = Color.FromArgb(105, 181, 255);
            btn_back.onHoverState.BorderRadius = 1;
            btn_back.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btn_back.onHoverState.BorderThickness = 1;
            btn_back.onHoverState.FillColor = Color.FromArgb(105, 181, 255);
            btn_back.onHoverState.ForeColor = Color.White;
            btn_back.onHoverState.IconLeftImage = null;
            btn_back.onHoverState.IconRightImage = null;
            btn_back.OnIdleState.BorderColor = Color.DodgerBlue;
            btn_back.OnIdleState.BorderRadius = 1;
            btn_back.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btn_back.OnIdleState.BorderThickness = 1;
            btn_back.OnIdleState.FillColor = Color.Maroon;
            btn_back.OnIdleState.ForeColor = Color.White;
            btn_back.OnIdleState.IconLeftImage = null;
            btn_back.OnIdleState.IconRightImage = null;
            btn_back.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btn_back.OnPressedState.BorderRadius = 1;
            btn_back.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btn_back.OnPressedState.BorderThickness = 1;
            btn_back.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btn_back.OnPressedState.ForeColor = Color.White;
            btn_back.OnPressedState.IconLeftImage = null;
            btn_back.OnPressedState.IconRightImage = null;
            btn_back.Size = new Size(126, 49);
            btn_back.TabIndex = 28;
            btn_back.TextAlign = ContentAlignment.MiddleCenter;
            btn_back.TextAlignment = HorizontalAlignment.Center;
            btn_back.TextMarginLeft = 0;
            btn_back.TextPadding = new Padding(0);
            btn_back.UseDefaultRadiusAndThickness = true;
            btn_back.Click += btn_back_Click;
            // 
            // btn_delete
            // 
            btn_delete.AllowAnimations = true;
            btn_delete.AllowMouseEffects = true;
            btn_delete.AllowToggling = false;
            btn_delete.AnimationSpeed = 200;
            btn_delete.AutoGenerateColors = false;
            btn_delete.AutoRoundBorders = false;
            btn_delete.AutoSizeLeftIcon = true;
            btn_delete.AutoSizeRightIcon = true;
            btn_delete.BackColor = Color.Transparent;
            btn_delete.BackColor1 = Color.Maroon;
            btn_delete.BackgroundImage = (Image)resources.GetObject("btn_delete.BackgroundImage");
            btn_delete.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btn_delete.ButtonText = "Delete";
            btn_delete.ButtonTextMarginLeft = 0;
            btn_delete.ColorContrastOnClick = 45;
            btn_delete.ColorContrastOnHover = 45;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            btn_delete.CustomizableEdges = borderEdges3;
            btn_delete.DialogResult = DialogResult.None;
            btn_delete.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btn_delete.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btn_delete.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btn_delete.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btn_delete.Font = new Font("Segoe UI", 10.2F, FontStyle.Bold, GraphicsUnit.Point);
            btn_delete.ForeColor = Color.White;
            btn_delete.IconLeftAlign = ContentAlignment.MiddleLeft;
            btn_delete.IconLeftCursor = Cursors.Default;
            btn_delete.IconLeftPadding = new Padding(11, 3, 3, 3);
            btn_delete.IconMarginLeft = 11;
            btn_delete.IconPadding = 10;
            btn_delete.IconRightAlign = ContentAlignment.MiddleRight;
            btn_delete.IconRightCursor = Cursors.Default;
            btn_delete.IconRightPadding = new Padding(3, 3, 7, 3);
            btn_delete.IconSize = 25;
            btn_delete.IdleBorderColor = Color.DodgerBlue;
            btn_delete.IdleBorderRadius = 1;
            btn_delete.IdleBorderThickness = 1;
            btn_delete.IdleFillColor = Color.Maroon;
            btn_delete.IdleIconLeftImage = null;
            btn_delete.IdleIconRightImage = null;
            btn_delete.IndicateFocus = false;
            btn_delete.Location = new Point(332, 392);
            btn_delete.Name = "btn_delete";
            btn_delete.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btn_delete.OnDisabledState.BorderRadius = 1;
            btn_delete.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btn_delete.OnDisabledState.BorderThickness = 1;
            btn_delete.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btn_delete.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btn_delete.OnDisabledState.IconLeftImage = null;
            btn_delete.OnDisabledState.IconRightImage = null;
            btn_delete.onHoverState.BorderColor = Color.FromArgb(105, 181, 255);
            btn_delete.onHoverState.BorderRadius = 1;
            btn_delete.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btn_delete.onHoverState.BorderThickness = 1;
            btn_delete.onHoverState.FillColor = Color.FromArgb(105, 181, 255);
            btn_delete.onHoverState.ForeColor = Color.White;
            btn_delete.onHoverState.IconLeftImage = null;
            btn_delete.onHoverState.IconRightImage = null;
            btn_delete.OnIdleState.BorderColor = Color.DodgerBlue;
            btn_delete.OnIdleState.BorderRadius = 1;
            btn_delete.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btn_delete.OnIdleState.BorderThickness = 1;
            btn_delete.OnIdleState.FillColor = Color.Maroon;
            btn_delete.OnIdleState.ForeColor = Color.White;
            btn_delete.OnIdleState.IconLeftImage = null;
            btn_delete.OnIdleState.IconRightImage = null;
            btn_delete.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btn_delete.OnPressedState.BorderRadius = 1;
            btn_delete.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btn_delete.OnPressedState.BorderThickness = 1;
            btn_delete.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btn_delete.OnPressedState.ForeColor = Color.White;
            btn_delete.OnPressedState.IconLeftImage = null;
            btn_delete.OnPressedState.IconRightImage = null;
            btn_delete.Size = new Size(113, 49);
            btn_delete.TabIndex = 27;
            btn_delete.TextAlign = ContentAlignment.MiddleCenter;
            btn_delete.TextAlignment = HorizontalAlignment.Center;
            btn_delete.TextMarginLeft = 0;
            btn_delete.TextPadding = new Padding(0);
            btn_delete.UseDefaultRadiusAndThickness = true;
            btn_delete.Click += btn_delete_Click;
            // 
            // btn_Update
            // 
            btn_Update.AllowAnimations = true;
            btn_Update.AllowMouseEffects = true;
            btn_Update.AllowToggling = false;
            btn_Update.AnimationSpeed = 200;
            btn_Update.AutoGenerateColors = false;
            btn_Update.AutoRoundBorders = false;
            btn_Update.AutoSizeLeftIcon = true;
            btn_Update.AutoSizeRightIcon = true;
            btn_Update.BackColor = Color.Transparent;
            btn_Update.BackColor1 = Color.Maroon;
            btn_Update.BackgroundImage = (Image)resources.GetObject("btn_Update.BackgroundImage");
            btn_Update.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btn_Update.ButtonText = "Update";
            btn_Update.ButtonTextMarginLeft = 0;
            btn_Update.ColorContrastOnClick = 45;
            btn_Update.ColorContrastOnHover = 45;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            btn_Update.CustomizableEdges = borderEdges4;
            btn_Update.DialogResult = DialogResult.None;
            btn_Update.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btn_Update.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btn_Update.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btn_Update.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btn_Update.Font = new Font("Segoe UI", 10.2F, FontStyle.Bold, GraphicsUnit.Point);
            btn_Update.ForeColor = Color.White;
            btn_Update.IconLeftAlign = ContentAlignment.MiddleLeft;
            btn_Update.IconLeftCursor = Cursors.Default;
            btn_Update.IconLeftPadding = new Padding(11, 3, 3, 3);
            btn_Update.IconMarginLeft = 11;
            btn_Update.IconPadding = 10;
            btn_Update.IconRightAlign = ContentAlignment.MiddleRight;
            btn_Update.IconRightCursor = Cursors.Default;
            btn_Update.IconRightPadding = new Padding(3, 3, 7, 3);
            btn_Update.IconSize = 25;
            btn_Update.IdleBorderColor = Color.DodgerBlue;
            btn_Update.IdleBorderRadius = 1;
            btn_Update.IdleBorderThickness = 1;
            btn_Update.IdleFillColor = Color.Maroon;
            btn_Update.IdleIconLeftImage = null;
            btn_Update.IdleIconRightImage = null;
            btn_Update.IndicateFocus = false;
            btn_Update.Location = new Point(184, 392);
            btn_Update.Name = "btn_Update";
            btn_Update.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btn_Update.OnDisabledState.BorderRadius = 1;
            btn_Update.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btn_Update.OnDisabledState.BorderThickness = 1;
            btn_Update.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btn_Update.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btn_Update.OnDisabledState.IconLeftImage = null;
            btn_Update.OnDisabledState.IconRightImage = null;
            btn_Update.onHoverState.BorderColor = Color.FromArgb(105, 181, 255);
            btn_Update.onHoverState.BorderRadius = 1;
            btn_Update.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btn_Update.onHoverState.BorderThickness = 1;
            btn_Update.onHoverState.FillColor = Color.FromArgb(105, 181, 255);
            btn_Update.onHoverState.ForeColor = Color.White;
            btn_Update.onHoverState.IconLeftImage = null;
            btn_Update.onHoverState.IconRightImage = null;
            btn_Update.OnIdleState.BorderColor = Color.DodgerBlue;
            btn_Update.OnIdleState.BorderRadius = 1;
            btn_Update.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btn_Update.OnIdleState.BorderThickness = 1;
            btn_Update.OnIdleState.FillColor = Color.Maroon;
            btn_Update.OnIdleState.ForeColor = Color.White;
            btn_Update.OnIdleState.IconLeftImage = null;
            btn_Update.OnIdleState.IconRightImage = null;
            btn_Update.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btn_Update.OnPressedState.BorderRadius = 1;
            btn_Update.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btn_Update.OnPressedState.BorderThickness = 1;
            btn_Update.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btn_Update.OnPressedState.ForeColor = Color.White;
            btn_Update.OnPressedState.IconLeftImage = null;
            btn_Update.OnPressedState.IconRightImage = null;
            btn_Update.Size = new Size(126, 49);
            btn_Update.TabIndex = 26;
            btn_Update.TextAlign = ContentAlignment.MiddleCenter;
            btn_Update.TextAlignment = HorizontalAlignment.Center;
            btn_Update.TextMarginLeft = 0;
            btn_Update.TextPadding = new Padding(0);
            btn_Update.UseDefaultRadiusAndThickness = true;
            btn_Update.Click += btn_Update_Click;
            // 
            // label3
            // 
            label3.AutoSize = true;
            label3.Font = new Font("Segoe UI", 10.2F, FontStyle.Bold, GraphicsUnit.Point);
            label3.ForeColor = Color.Maroon;
            label3.Location = new Point(341, 171);
            label3.Name = "label3";
            label3.Size = new Size(67, 23);
            label3.TabIndex = 30;
            label3.Text = "gender";
            // 
            // dgv_emp
            // 
            dgv_emp.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = Color.FromArgb(248, 251, 255);
            dataGridViewCellStyle1.ForeColor = Color.Black;
            dgv_emp.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            dgv_emp.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgv_emp.BorderStyle = BorderStyle.None;
            dgv_emp.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
            dgv_emp.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold, GraphicsUnit.Point);
            dataGridViewCellStyle2.ForeColor = Color.White;
            dataGridViewCellStyle2.SelectionBackColor = Color.FromArgb(24, 115, 204);
            dataGridViewCellStyle2.SelectionForeColor = Color.White;
            dataGridViewCellStyle2.WrapMode = DataGridViewTriState.True;
            dgv_emp.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            dgv_emp.ColumnHeadersHeight = 40;
            dgv_emp.CurrentTheme.AlternatingRowsStyle.BackColor = Color.FromArgb(248, 251, 255);
            dgv_emp.CurrentTheme.AlternatingRowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold, GraphicsUnit.Point);
            dgv_emp.CurrentTheme.AlternatingRowsStyle.ForeColor = Color.Black;
            dgv_emp.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
            dgv_emp.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = Color.Black;
            dgv_emp.CurrentTheme.BackColor = Color.White;
            dgv_emp.CurrentTheme.GridColor = Color.FromArgb(221, 238, 255);
            dgv_emp.CurrentTheme.HeaderStyle.BackColor = Color.DodgerBlue;
            dgv_emp.CurrentTheme.HeaderStyle.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold, GraphicsUnit.Point);
            dgv_emp.CurrentTheme.HeaderStyle.ForeColor = Color.White;
            dgv_emp.CurrentTheme.HeaderStyle.SelectionBackColor = Color.FromArgb(24, 115, 204);
            dgv_emp.CurrentTheme.HeaderStyle.SelectionForeColor = Color.White;
            dgv_emp.CurrentTheme.Name = null;
            dgv_emp.CurrentTheme.RowsStyle.BackColor = Color.White;
            dgv_emp.CurrentTheme.RowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold, GraphicsUnit.Point);
            dgv_emp.CurrentTheme.RowsStyle.ForeColor = Color.Black;
            dgv_emp.CurrentTheme.RowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
            dgv_emp.CurrentTheme.RowsStyle.SelectionForeColor = Color.Black;
            dataGridViewCellStyle3.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = Color.White;
            dataGridViewCellStyle3.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold, GraphicsUnit.Point);
            dataGridViewCellStyle3.ForeColor = Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = Color.FromArgb(210, 232, 255);
            dataGridViewCellStyle3.SelectionForeColor = Color.Black;
            dataGridViewCellStyle3.WrapMode = DataGridViewTriState.False;
            dgv_emp.DefaultCellStyle = dataGridViewCellStyle3;
            dgv_emp.EnableHeadersVisualStyles = false;
            dgv_emp.GridColor = Color.FromArgb(221, 238, 255);
            dgv_emp.HeaderBackColor = Color.DodgerBlue;
            dgv_emp.HeaderBgColor = Color.Empty;
            dgv_emp.HeaderForeColor = Color.White;
            dgv_emp.Location = new Point(486, -1);
            dgv_emp.Name = "dgv_emp";
            dgv_emp.RowHeadersVisible = false;
            dgv_emp.RowHeadersWidth = 51;
            dgv_emp.RowTemplate.Height = 40;
            dgv_emp.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgv_emp.Size = new Size(658, 537);
            dgv_emp.TabIndex = 31;
            dgv_emp.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            dgv_emp.CellContentClick += dgv_emp_CellContentClick;
            // 
            // comboRole
            // 
            comboRole.Font = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point);
            comboRole.ForeColor = Color.Maroon;
            comboRole.FormattingEnabled = true;
            comboRole.Items.AddRange(new object[] { "E", "A" });
            comboRole.Location = new Point(159, 343);
            comboRole.Name = "comboRole";
            comboRole.Size = new Size(151, 28);
            comboRole.TabIndex = 32;
            comboRole.Text = "Role";
            // 
            // Employee
            // 
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = SystemColors.ActiveCaption;
            ClientSize = new Size(1145, 536);
            Controls.Add(comboRole);
            Controls.Add(dgv_emp);
            Controls.Add(label3);
            Controls.Add(btn_add);
            Controls.Add(btn_back);
            Controls.Add(btn_delete);
            Controls.Add(btn_Update);
            Controls.Add(txt_password);
            Controls.Add(txt_phone);
            Controls.Add(label1);
            Controls.Add(label2);
            Controls.Add(numage);
            Controls.Add(numsalary);
            Controls.Add(comboBoxgender);
            Controls.Add(bunifuLabel1);
            Controls.Add(emp_name);
            FormBorderStyle = FormBorderStyle.None;
            Name = "Employee";
            Text = "Employee";
            Load += Employee_Load;
            ((System.ComponentModel.ISupportInitialize)numage).EndInit();
            ((System.ComponentModel.ISupportInitialize)numsalary).EndInit();
            ((System.ComponentModel.ISupportInitialize)dgv_emp).EndInit();
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion
        private NumericUpDown numage;
        private NumericUpDown numsalary;
        private ComboBox comboBoxgender;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox emp_name;
        private Label label2;
        private Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox txt_phone;
        private Bunifu.UI.WinForms.BunifuTextBox txt_password;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btn_add;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btn_back;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btn_delete;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btn_Update;
        private Label label3;
        private Bunifu.UI.WinForms.BunifuDataGridView dgv_emp;
        private ComboBox comboRole;
    }
}